# MikuDream UUID Uploader 配置文件

# 数据库配置
database:
  host: "your_host"
  port: 3306
  database: "your_database"
  username: "your_username"
  password: "your_password"
  table: your_table
  
# 插件设置
settings:
  # 是否在玩家加入时自动上传UUID
  auto_upload_on_join: true
  
  # 是否在玩家退出时记录最后在线时间
  record_last_seen: flase
  
  # 上传间隔（秒），防止频繁上传
  upload_cooldown: 300
  
  # 是否启用调试模式
  debug: false
  
# 消息配置
messages:
  prefix: "&8[&bMikuDream&8] &r"
  upload_success: "&a玩家UUID上传成功: {player} ({uuid})"
  upload_failed: "&c玩家UUID上传失败: {player}"
  reload_success: "&a配置重新加载成功"
  no_permission: "&c您没有权限使用此命令"
  player_not_found: "&c玩家 {player} 未找到"
  database_error: "&c数据库连接错误，请检查配置"
  bind_code_own: "&a您的配对码: &e{bind_code}"
  bind_code_show: "&a玩家 {player} 的配对码: &e{bind_code}"
  bind_code_generated: "&a已为您生成配对码: &e{bind_code}"
  bind_code_error: "&c获取配对码失败" 
