name: MikuDreamUUIDUploader
version: 1.0.4
main: com.mikudream.uuiduploader.MikuDreamUUIDPlugin
api-version: 1.21
author: MikuDream
description: 上传玩家UUID到phpMyAdmin数据库

commands:
  uuidupload:
    description: 手动上传玩家UUID到数据库
    usage: /<command> [玩家名]
    permission: mikudream.uuidupload.admin
  uuidreload:
    description: 重新加载插件配置
    usage: /<command>
    permission: mikudream.uuidupload.admin
  bind:
    description: 查看玩家配对码
    usage: /<command> [玩家名]
    permission: mikudream.uuidupload.bind

permissions:
  mikudream.uuidupload.admin:
    description: 允许使用管理命令
    default: op
  mikudream.uuidupload.upload:
    description: 允许上传UUID
    default: true
  mikudream.uuidupload.bind:
    description: 允许查看配对码
    default: true 